using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum ShieldModType
{
	ShieldProject,
	Flagship
}

[System.Serializable]
public class ShieldMod
{
	public Unit from;
	public float shieldPercent;
	public ShieldModType shieldModType;

	public ShieldMod(Unit u, float p, ShieldModType t)
	{
		from = u;
		shieldPercent = p;
		shieldModType = t;
	}
}

public static class ShieldModUtils
{
	public static string GetDisplayDesc(ShieldModType shieldModType)
	{
		switch (shieldModType)
		{
			case ShieldModType.ShieldProject:
				return "Shield is projected onto this unit by another allied unit";
			case ShieldModType.Flagship:
				return "Shield is generated by this flagship's defensive systems";
			default:
				return "default";
		}
	}
}